name: checkout-flow
on: push

jobs:
  no-checkout:
    runs-on: ubuntu-latest
    steps:
    - name: cat readme fail
      run: cat README.md

  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4