name: if-2
on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: get event name
      run: exit 1

  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: get event name
      run: echo HIHI