name: output
on: push

jobs:
  create-out:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.check-o.outputs.test }}
    steps:
    - name: echo
      id: check-o
      run: echo "test=hello" >> $GITHUB_OUTPUT
    - name: check output
      run: echo ${{ steps.check-o.outputs.test }}

  get:
    runs-on: ubuntu-latest
    needs: [create-out]
    steps:
    - name: get out
      run: echo ${{ needs.create-out.outputs.test }}