name: artifact-flow
on: push

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo hello-wo > hello.txt
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact-test
        path: ./hello.txt
      
  download-artifcat:
    runs-on: ubuntu-latest
    needs: [upload-artifact]
    steps:
    - name: download artifact
      uses: actions/download-artifact@v3
      with:
        name: artifact-test
        path: ./
    - name: echo
      run: cat hello.txt
