name: issue
on:
  issues:
    types: [opened]

jobs:
  pull-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world

    - name: step2
      run: |
        echo hhhhhh
        echo dhhdhdhdh