name: output
on: push

jobs:
  create-out:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      id: check-o
      run: echo "test=hello" >> $GITHUB_OUTPUT
    - name: check output
      run: echo ${{ steps.check-o.outputs.test }}